<h1>Plans</h1>
<table><tr><th>Name</th><th>Scheme</th><th>M/Q/Y</th><th>Trial</th><th>Included Modules</th><th>Edit</th></tr><?php foreach($plans as $p): ?><tr><td><?= htmlspecialchars($p['plan_name']) ?></td><td><?= htmlspecialchars($p['scheme_key']) ?></td><td>₹<?= (float)$p['monthly_price'] ?>/₹<?= (float)$p['quarterly_price'] ?>/₹<?= (float)$p['yearly_price'] ?></td><td><?= (int)$p['trial_days'] ?>d</td><td><?= htmlspecialchars(implode(', ',$p['included_modules'])) ?></td><td>
<form method="post" class="card"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars((string)$csrfToken) ?>"><input type="hidden" name="plan_key" value="<?= htmlspecialchars($p['plan_key']) ?>">
<input name="plan_name" value="<?= htmlspecialchars($p['plan_name']) ?>"><input name="description" value="<?= htmlspecialchars($p['description']) ?>"><input name="scheme_key" value="<?= htmlspecialchars($p['scheme_key']) ?>">
<input name="monthly_price" type="number" step="0.01" value="<?= htmlspecialchars((string)$p['monthly_price']) ?>"><input name="quarterly_price" type="number" step="0.01" value="<?= htmlspecialchars((string)$p['quarterly_price']) ?>"><input name="yearly_price" type="number" step="0.01" value="<?= htmlspecialchars((string)$p['yearly_price']) ?>"><input name="trial_days" type="number" value="<?= (int)$p['trial_days'] ?>">
<select name="included_modules_selector" multiple size="8"><?php foreach($modules as $m): ?><option value="<?= htmlspecialchars($m['module_key']) ?>" <?= in_array($m['module_key'],$p['included_modules'],true)?'selected':'' ?>><?= htmlspecialchars($m['module_name']) ?></option><?php endforeach; ?></select>
<input type="hidden" name="included_modules" value="<?= htmlspecialchars(implode(',', $p['included_modules'])) ?>" class="plan-modules-hidden">
<label><input type="checkbox" name="recommended_flag" <?= !empty($p['recommended_flag'])?'checked':'' ?>> recommended</label><label><input type="checkbox" name="active_flag" <?= !empty($p['active_flag'])?'checked':'' ?>> active</label><button class="btn">Save</button></form>
</td></tr><?php endforeach; ?></table>
<script>document.querySelectorAll('form').forEach(f=>{const s=f.querySelector('select[name="included_modules"]');const h=f.querySelector('.plan-modules-hidden');if(!s||!h)return;const sync=()=>{h.value=[...s.selectedOptions].map(o=>o.value).join(',')};s.addEventListener('change',sync);sync();});</script>
