<h1>Plan Registry</h1>
<form method="get" class="card inline-form">
    <input name="q" value="<?= htmlspecialchars((string) ($search ?? '')) ?>" placeholder="Search plan key/name/description">
    <select name="scheme_key"><option value="all">All schemes</option><?php foreach($schemes as $s): ?><option value="<?= htmlspecialchars((string) $s['scheme_key']) ?>" <?= ($schemeFilter ?? 'all')===$s['scheme_key']?'selected':'' ?>><?= htmlspecialchars((string) $s['scheme_name']) ?></option><?php endforeach; ?></select>
    <button class="btn">Filter</button>
</form>
<table><tr><th>Plan</th><th>Scheme</th><th>Modules</th><th>Price M/Q/Y</th><th>Trial</th><th>Flags</th><th>Updated</th><th>Edit</th></tr><?php foreach($plans as $p): ?><tr><td><?= htmlspecialchars((string) $p['plan_name']) ?><br><small><?= htmlspecialchars((string) $p['plan_key']) ?></small></td><td><?= htmlspecialchars((string) $p['scheme_key']) ?></td><td><?= count((array) $p['included_modules']) ?> modules<br><small><?= htmlspecialchars(implode(', ', (array)$p['included_modules'])) ?></small></td><td>₹<?= (float)$p['monthly_price'] ?>/₹<?= (float)$p['quarterly_price'] ?>/₹<?= (float)$p['yearly_price'] ?></td><td><?= (int)$p['trial_days'] ?>d</td><td><?= !empty($p['recommended_flag'])?'recommended':'' ?> <?= !empty($p['active_flag'])?'active':'inactive' ?></td><td><?= htmlspecialchars((string) ($p['updated_at'] ?? '-')) ?></td><td>
<form method="post" class="card compact-form"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars((string)$csrfToken) ?>"><input type="hidden" name="plan_key" value="<?= htmlspecialchars((string)$p['plan_key']) ?>">
<input name="plan_name" value="<?= htmlspecialchars((string)$p['plan_name']) ?>"><textarea name="description"><?= htmlspecialchars((string)$p['description']) ?></textarea><input name="scheme_key" value="<?= htmlspecialchars((string)$p['scheme_key']) ?>">
<input name="monthly_price" type="number" step="0.01" value="<?= htmlspecialchars((string)$p['monthly_price']) ?>"><input name="quarterly_price" type="number" step="0.01" value="<?= htmlspecialchars((string)$p['quarterly_price']) ?>"><input name="yearly_price" type="number" step="0.01" value="<?= htmlspecialchars((string)$p['yearly_price']) ?>"><input name="trial_days" type="number" value="<?= (int)$p['trial_days'] ?>">
<select name="included_modules_selector" multiple size="6"><?php foreach($modules as $m): ?><option value="<?= htmlspecialchars((string)$m['module_key']) ?>" <?= in_array($m['module_key'], (array) $p['included_modules'], true)?'selected':'' ?>><?= htmlspecialchars((string)$m['module_name']) ?></option><?php endforeach; ?></select>
<input type="hidden" name="included_modules" value="<?= htmlspecialchars(implode(',', (array) $p['included_modules'])) ?>" class="plan-modules-hidden">
<input name="excluded_modules" value="<?= htmlspecialchars(implode(',', (array) ($p['excluded_modules'] ?? []))) ?>" placeholder="excluded module keys csv">
<label><input type="checkbox" name="recommended_flag" <?= !empty($p['recommended_flag'])?'checked':'' ?>> recommended</label><label><input type="checkbox" name="active_flag" <?= !empty($p['active_flag'])?'checked':'' ?>> active</label><button class="btn">Save</button></form>
</td></tr><?php endforeach; ?></table>
<script>document.querySelectorAll('form').forEach(f=>{const s=f.querySelector('select[name="included_modules_selector"]');const h=f.querySelector('.plan-modules-hidden');if(!s||!h)return;const sync=()=>{h.value=[...s.selectedOptions].map(o=>o.value).join(',')};s.addEventListener('change',sync);sync();});</script>
